name: Java Tomcat CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    # 1️⃣ Get Source Code
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2️⃣ Install Java
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # 3️⃣ Build WAR
    - name: Build WAR
      run: mvn clean package -DskipTests

    # 4️⃣ Upload artifact to EC2 (RENAME to fixed name)
    - name: Copy WAR to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: ${{ secrets.EC2_PORT }}
        source: "target/*.war"
        target: "/home/deploy/"
        strip_components: 1

    # 5️⃣ Deploy in Tomcat (REAL CD)
    
    - name: Deploy in Tomcat
      uses: appleboy/ssh-action@v1.0.3
      with:
       host: ${{ secrets.EC2_HOST }}
       username: ${{ secrets.EC2_USER }}
       key: ${{ secrets.EC2_KEY }}
       port: ${{ secrets.EC2_PORT }}
       script: |

         echo "1. Stop Tomcat"
         pkill -f tomcat || true
         sleep 5

         echo "2. Clean old deployment"
         rm -rf /root/tomcat/work/*
         rm -rf /root/tomcat/temp/*
         rm -rf /root/tomcat/logs/*
         rm -rf /root/tomcat/webapps/ROOT
         rm -f  /root/tomcat/webapps/ROOT.war
  
         echo "3. Copy new WAR"
         cp /home/deploy/*.war /root/tomcat/webapps/ROOT.war
  
         echo "4. Start Tomcat fresh"
         nohup /root/tomcat/bin/startup.sh >/dev/null 2>&1 &
  
         echo "5. Wait for extraction"
         sleep 25
  
         echo "6. Verify deployment"
         ls -ltr /root/tomcat/webapps
  
