name: Java Tomcat CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    # 1. Checkout Code
    - name: Checkout Source
      uses: actions/checkout@v4

    # 2. Setup Java
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # 3. Build WAR
    - name: Build WAR
      run: mvn clean package

    # 4. Upload WAR to EC2
    - name: Upload WAR to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: ${{ secrets.EC2_PORT }}
        source: "target/*.war"
        target: "/root/"

    # 5. Deploy Application
    - name: Deploy to Tomcat
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: ${{ secrets.EC2_PORT }}
        script: |
          echo "Stopping Tomcat"
          pkill -f tomcat || true

          echo "Cleaning old app"
          rm -rf /root/tomcat/webapps/ROOT
          rm -f /root/tomcat/webapps/ROOT.war

          echo "Deploying new WAR"
          WAR_NAME=$(ls /root/*.war | head -n 1)
          cp $WAR_NAME /root/tomcat/webapps/ROOT.war

          echo "Starting Tomcat"
          /root/tomcat/bin/startup.sh

          echo "Deployment Completed"
