name: Java Tomcat CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    # 1. Checkout Code
    - name: Checkout Source
      uses: actions/checkout@v4

    # 2. Setup Java
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # 3. Build WAR
    - name: Build WAR
      run: mvn clean package

    # 4. Upload WAR to EC2
    - name: Upload WAR to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: ${{ secrets.EC2_PORT }}
        source: "target/*.war"
        target: "/home/deploy/"

    # 5. Deploy Application
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: ${{ secrets.EC2_PORT }}
        script: |
          echo "Stopping Tomcat"
          sudo /root/tomcat/bin/shutdown.sh
          sleep 5

          echo "Removing old app"
          sudo rm -rf /root/tomcat/webapps/ROOT*

          echo "Deploying new WAR"
          sudo mv /home/deploy/*.war /root/tomcat/webapps/ROOT.war

          echo "Starting Tomcat"
          sudo /root/tomcat/bin/startup.sh
