name: Java Tomcat CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    # 1️⃣ Get Source Code
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2️⃣ Install Java
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # 3️⃣ Build WAR
    - name: Build WAR
      run: mvn clean package -DskipTests

    # 4️⃣ Upload artifact to EC2 (RENAME to fixed name)
    - name: Copy WAR to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: ${{ secrets.EC2_PORT }}
        source: "target/*.war"
        target: "/home/deploy/"
        strip_components: 1

    # 5️⃣ Deploy in Tomcat (REAL CD)
    - name: Deploy Application
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: ${{ secrets.EC2_PORT }}
        script: |

          echo "Stopping Tomcat"
          sudo /root/tomcat/bin/shutdown.sh || true
          sleep 10
        
          echo "Remove old deployments"
          sudo rm -rf /root/tomcat/webapps/ROOT
          sudo rm -f /root/tomcat/webapps/ROOT.war
          sudo rm -rf /root/tomcat/work/*
          sudo rm -rf /root/tomcat/temp/*
        
          echo "Remove old uploaded WAR"
          rm -f /home/deploy/*.war

          echo "Move NEW war to tomcat"
          sudo mv /home/deploy/*.war /root/tomcat/webapps/ROOT.war
        
          echo "Starting Tomcat"
          sudo /root/tomcat/bin/startup.sh
        
          echo "Waiting deploy"
          sleep 25
        
          echo "Deployment Finished"
