name: Java Tomcat CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build WAR
      run: mvn clean package

    - name: Copy WAR to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: ${{ secrets.EC2_PORT }}
        source: "target/*.war"
        target: "/home/deploy/"

    
    - name: Deploy in Tomcat
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: ${{ secrets.EC2_PORT }}
        

        script: |

          echo "Stopping Tomcat"
          sudo /root/tomcat/bin/shutdown.sh || true
          sleep 8
        
          echo "Cleaning previous deployment"
          sudo rm -rf /root/tomcat/webapps/ROOT
          sudo rm -f /root/tomcat/webapps/ROOT.war
          sudo rm -rf /root/tomcat/work/*
          sudo rm -rf /root/tomcat/temp/*
        
          echo "Copying new WAR"
          sudo cp /home/deploy/*.war /root/tomcat/webapps/ROOT.war
        
          echo "Starting Tomcat"
          sudo /root/tomcat/bin/startup.sh
        
          echo "Waiting for Tomcat to extract WAR"
          sleep 25
        
          echo "Deployment Finished"

    
