name: Java Tomcat CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build WAR
      run: mvn clean package

    # Upload to deploy user home (NOT ROOT)
    - name: Upload WAR to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: ${{ secrets.EC2_PORT }}
        source: "target/*.war"
        target: "/home/deploy/"

    # Deploy using sudo
    - name: Deploy to Tomcat
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: ${{ secrets.EC2_PORT }}
        script: |

          echo "Stopping Tomcat"
          sudo pkill -f tomcat || true

          echo "Cleaning old app"
          sudo rm -rf /root/tomcat/webapps/ROOT
          sudo rm -f /root/tomcat/webapps/ROOT.war

          echo "Copy new WAR"
          WAR_NAME=$(ls /home/deploy/*.war | head -n 1)
          sudo cp $WAR_NAME /root/tomcat/webapps/ROOT.war

          echo "Starting Tomcat"
          sudo /root/tomcat/bin/startup.sh

          echo "Deployment Successful"
